<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.10" />
    <PackageReference Include="System.IO.Ports" Version="10.0.10" />
    <PackageReference Include="System.Management" Version="10.0.9" />
    <PackageReference Include="Twilio" Version="7.14.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ObservatorySafety.NINA\ObservatorySafety.NINA.csproj" />
    <ProjectReference Include="..\ObservatorySafety.Core\ObservatorySafety.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ASCOM.Astrometry">
      <HintPath>..\..\lib\ASCOM.Astrometry.dll</HintPath>
    </Reference>
    <Reference Include="ASCOM.Attributes">
      <HintPath>..\..\lib\ASCOM.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="ASCOM.Cache">
      <HintPath>..\..\lib\ASCOM.Cache.dll</HintPath>
    </Reference>
    <Reference Include="ASCOM.Controls">
      <HintPath>..\..\lib\ASCOM.Controls.dll</HintPath>
    </Reference>
    <Reference Include="ASCOM.DeviceInterfaces">
      <HintPath>..\..\lib\ASCOM.DeviceInterfaces.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="ASCOM.DriverAccess">
      <HintPath>..\..\lib\ASCOM.DriverAccess.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="ASCOM.Exceptions">
      <HintPath>..\..\lib\ASCOM.Exceptions.dll</HintPath>
    </Reference>

    <Reference Include="ASCOM.Internal.Extensions">
      <HintPath>..\..\lib\ASCOM.Internal.Extensions.dll</HintPath>
    </Reference>

    <Reference Include="ASCOM.SettingsProvider">
      <HintPath>..\..\lib\ASCOM.SettingsProvider.dll</HintPath>
    </Reference>

    <Reference Include="ASCOM.Utilities">
      <HintPath>..\..\lib\ASCOM.Utilities.dll</HintPath>
    </Reference>

    <Reference Include="ASCOM.Utilities.Video">
      <HintPath>..\..\lib\ASCOM.Utilities.Video.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
